#!/usr/bin/perl
#
# This code is distributed under the terms of the GPL
#
# (c) 2006-2009 marco.s - http://update-accelerator.advproxy.net
#

$scriptpath=substr($0,0,rindex($0,"/"));

system("$scriptpath/install.sh -i");

